name: pattern_m
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

import_sorter:
  comments: false
